name: Patchwork
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
baseurl: /_site

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
